### ISSUE TITLE
need to require 'active_record' instead of 'activerecord'

### ISSUE THREAD

**Issue by darrinholst** [nakajima/fixjour#3]
getting a new deprecation warning as of rails 2.3.5...

DEPRECATION WARNING: require "activerecord" is deprecated and will be removed in Rails 3. Use require "active_record" instead..

I'd fork, fix, push, pull request ya, but it's probably just easier for you to add the '_' at http://github.com/nakajima/fixjour/blob/master/lib/fixjour.rb#L3

**Comment by nakajima** [comment]
Ah, thanks for the heads up. Fixed in 2fad9788991070fac69acfc513d6570b21b49520.
