### ISSUE TITLE
Current gem broken in rubygems.org

### ISSUE THREAD

**Issue by edward** [nakajima/fixjour#5]
I tried to do a `gem install fixjour` (June 7th), but got this:

```
While executing gem ... (Zlib::GzipFile::Error)
    not in gzip format
```

**Comment by nakajima** [comment]
Wow, that's strange. Seems like that might be a rubygems.org issue but I'll also take a look from my end.

**Comment by edward** [comment]
Sweet, thanks! I <3 fixjour; it was so sad to see it be broken in the wild.

**Comment by edward** [comment]
I noticed that the gem was working again. My money is on a Rubygems breakage a while back.
